config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  root to: 'timeslots#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :set_timeslot, only: [:show, :edit, :update, :destroy]

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
  end

  # GET /timeslots/new
  def new
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)

    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
        format.json { render :show, status: :created, location: @timeslot }
      else
        format.html { render :new }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timeslots/1
  # PATCH/PUT /timeslots/1.json
  def update
    respond_to do |format|
      if @timeslot.update(timeslot_params)
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeslot }
      else
        format.html { render :edit }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot.destroy
    respond_to do |format|
      format.html { redirect_to timeslots_url, notice: 'Timeslot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeslot_params
      params.require(:timeslot).permit(:start)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-footer">

<p></p>

    </div>  

	</div>
</div>

app/views/layouts/_navbar.html.erb
  
<nav class="navbar navbar-expand-sm navbar-dark bg-success">
    <%= link_to "Marshes Winter Academy", root_path, class:"navbar-brand" %>




  <!-- Collapsable button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link">
          <%= link_to '#' do %>
              <i class="fas fa-calendar "></i>Calendar
          <% end %>
        </a>
      </li>
      <li class="nav-item">

      </li>
      <li class="nav-item">
        <a class="nav-link">
          <%= link_to '#' do %>
              <i class="fas fa-user"></i> Profile
          <% end %>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link">
          <%= link_to '#', method: :delete do %>
              <i class="fas fa-sign-out-alt "></i> Signout
          <% end %>
        </a>
      </li>



    </ul>
  </div>





</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marshesgolfv6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 
    <body>

      <%= render 'layouts/navbar'  %>



        <div id="main-container" class="container-fluid" >
            <%= yield %>
        </div>
        

    </body>

      <%= render 'layouts/footer'  %>







</html>

app/views/timeslots/_form.html.erb
<%= form_with(model: timeslot, local: true) do |form| %>
  <% if timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
        <% timeslot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start %>
    <%= form.time_select :start %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing Timeslot</h1>

<%= render 'form', timeslot: @timeslot %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timeslots</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= timeslot.start %></td>
        <td><%= link_to 'Show', timeslot %></td>
        <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
        <td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeslot', new_timeslot_path %>



<h1>  test

<i class="fas fa-store"></i>
<i class="fas fa-calendar-alt"></i>


</h1>



<h1>Hello World</h1>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
  Tooltip on top
</button>

app/views/timeslots/new.html.erb
<h1>New Timeslot</h1>

<%= render 'form', timeslot: @timeslot %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @timeslot.start %>
</p>

<%= link_to 'Edit', edit_timeslot_path(@timeslot) %> |
<%= link_to 'Back', timeslots_path %>